### PR TITLE
Release 0.3.2

### PR DESCRIPTION
**Pull request by SpheMakh**
Upgrade to Casa 5.1

### CODE REVIEW

**Comment by SpheMakh** [comment]
Do not merge yet

**Comment by SpheMakh** [comment]
retest this please

**Comment by SpheMakh** [comment]
@bennahugo I thought every test runs in a new folder. Why is it complaining about the MS already existing 
```
2018-03-20 11:29:30	SEVERE	split::::	Output MS /home/jenkins/msdir/12A-405.sb7601493.eb10633016.56086.127048738424-corr.ms already exists - will not overwrite it.
```

**Comment by bennahugo** [comment]
@SpheMakh It does run in its own folder. The job isn't being run twice?

**Comment by SpheMakh** [comment]
@bennahugo I'm not sure how it would be run twice. Is that even possible?

**Comment by SpheMakh** [comment]
Closing this for now.

**Pull request closed without merging**
