### PR TITLE
Upgrade WSClean to v2.5

### LINKED ISSUE #221: Upgrade WSClean to 2.5
As per @paoloserra 's request.

### PR DESCRIPTION
**Pull request by bennahugo**
This upgrades WSClean to version 2.5 released 2017-12-01.

Changelog:
 - Add compatibility mode for specifying padding through trim and npix
 - Add compatibility mode for changed cli argument names

Fixes #221

### CODE REVIEW

**Comment by SpheMakh** [comment]
The stimela/wsclean:0.3.2dev image couldn't be found. Did you push this bad boy to the docker hub?

**Comment by bennahugo** [comment]
@SpheMakh Clearly not done now

**Comment by bennahugo** [comment]
retest this please

**Comment by bennahugo** [comment]
@SpheMakh I see you released 0.3.1 again, so this can go in

**Comment by SpheMakh** [comment]
I could only do it because the PyPI deployment had failed with the initial release of 0.3.1. Can't do it now, this will have to be in the next release

**Comment by bennahugo** [comment]
@paoloserra this is to preserve backwards compatibility of the interface - if we change this then all our other reduction scripts will be broken

**Comment by bennahugo** [comment]
@paoloserra if the trim key is ignored then there is a bug in meerkathi

**Comment by paoloserra** [comment]
That may well be, but I would be in favour of just adapting meerkathi to the new wsclean, and use padding+npix/size instead of trim+npix/size .

**Comment by o-smirnov** [comment]
> That may well be, but I would be in favour of just adapting meerkathi to the new wsclean, and use padding+npix/size

Agreed, it's a far more natural way to specify things. Andre should have done that from the start...

**Pull request merged**
