### PR TITLE
upgrade katdal

### PR DESCRIPTION
**Pull request by SpheMakh**
- use katdal 0.12

### CODE REVIEW

**Comment by SpheMakh** [comment]
A few bugs snuck in when I forced a couple of PRs during the MeerKATHI busy week. This latest commit should fix them.

**Comment by SpheMakh** [comment]
All tests ran successfully, but the test returns a failure. Any ideas @bennahugo

**Comment by bennahugo** [comment]
I've fixed the tests (I hope...) on my PR

**Comment by bennahugo** [comment]
PR obviously an acronym for prayer request...

**Comment by SpheMakh** [comment]
May the Lord open

**Pull request merged**
