### PR TITLE
Test podman

### PR DESCRIPTION
**Pull request by SpheMakh**
- add podman to jenkins ci test

### CODE REVIEW

**Comment by SpheMakh** [comment]
not sure what's happeing here
```
Running: podman pull docker.io/stimela/casa:1.2.0
Error: could not get runtime: error opening database /var/lib/jenkins/jobs/PR_stimela/workspace/88/.local/share/containers/storage/libpod/bolt_state.db: invalid argument
```

**Comment by bennahugo** [comment]
retest this please

**Comment by bennahugo** [comment]
retest this please

**Comment by bennahugo** [comment]
retest this please

**Pull request closed without merging**
