### PR TITLE
various parameter fixes

### LINKED ISSUE #420: Catdagger does not run within singularity
```
INFO:STIMELA:Adding cab '/home/hugo/STIMELA_IMAGES/stimela_pybdsf_1.0.1.img' to recipe. The container will be named 'find_sources'
Traceback (most recent call last):
  File "/home/hugo/venvstimela/bin/stimela", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/hugo/stimela/bin/stimela", line 13, in <module>
    stimela.main([a for a in sys.argv[1:]])
  File "/home/hugo/stimela/stimela/__init__.py", line 638, in main
    _cmd(argv)
  File "/home/hugo/stimela/stimela/__init__.py", line 302, in run
    exec(stdr.read(), _globals)
  File "<string>", line 451, in <module>
  File "<string>", line 230, in sourcefind_and_subtract
  File "/home/hugo/stimela/stimela/recipe.py", line 667, in add
    time_out=time_out)
  File "/home/hugo/stimela/stimela/recipe.py", line 228, in singularity_job
    self.recipe.stimela_path, _cab.task), "/scratch/code", "ro")
  File "/home/hugo/stimela/stimela/singularity.py", line 62, in add_volume
    raise IOError("Path {0} cannot be mounted on container: File doesn't exist".format(host))
IOError: Path /home/hugo/stimela/stimela/cargo/cab/dagger/src/ cannot be mounted on container: File doesn't exist
```

### PR DESCRIPTION
**Pull request by bennahugo**
Fixes #420 and a slew of other ddfacet and cubical parameters including modellist pattern non-recognition.

### CODE REVIEW

**Comment by bennahugo** [comment]
retest this please

**Comment by bennahugo** [comment]
@SpheMakh ok I don't think I will be able to get the testing back up and running for this. I'm going to disable udocker in this branch and run the tests with docker, because the container running listobs takes 5 minutes and times out. On other occasions it runs through.

**Comment by bennahugo** [comment]
In the mean time while I wait for Andre to get back to me my changes tricolour and cubical are on my various fixes branch if you want to give that a go @o-smirnov.

Please don't merge this branch until the tests pass

**Comment by SpheMakh** [comment]
The kat-7 test is now going through, but I missed merge conflicts in the singularity test

**Comment by SpheMakh** [comment]
Success!

**Comment by SpheMakh** [comment]
Success!

**Comment by bennahugo** [comment]
Success? the tick box is cross?

**Comment by KshitijT** [comment]
@bennahugo, is the new cubical parset and options part of this?

**Comment by bennahugo** [comment]
only the model list options not the degridder based predict

**Comment by KshitijT** [comment]
The new way of implementing the model-list parameters too?

**Comment by bennahugo** [comment]
yes. Once we make the next release of cubical the degridding options can be added

**Comment by KshitijT** [comment]
Awesome.

**Pull request merged**
