### PR TITLE
Build casacore with more cores

### PR DESCRIPTION
**Pull request by bennahugo**
Should build casacore with multiple cores... could be why it times out on Dockerhub

### CODE REVIEW

**Comment by SpheMakh** [comment]
These are the specs of the machine that dockerhub uses to build images

- 2 GB RAM
- 1 CPU
- 30 GB Disk Space

There is also a 2 hour time limit (this is what gets us I suppose)

https://github.com/moby/moby/issues/21093

**Comment by bennahugo** [comment]
1CPU or 1 multicore cpu? No way we can build it in that time frame with a single core. Might as well stick to a fast recompilation for own sanity?

**Comment by bennahugo** [comment]
Pushed the new image manually to the hub

**Comment by bennahugo** [comment]
retest this please

**Pull request merged**
