### PR TITLE
Wsclean/add parameter

### PR DESCRIPTION
**Pull request by Athanaseus**
Padding parameter

### CODE REVIEW

**Comment by SpheMakh** [comment]
Pinging @bennahugo

**Comment by bennahugo** [comment]
ok to test

**Comment by bennahugo** [comment]
@Athanaseus this breaks backward compatibility of scripts. I specifically keep the old interface alive for this reason?

**Comment by bennahugo** [comment]
We can maybe override options if the padding option is specified, but I don't think we should remove any of the old interface options

**Pull request merged**
