### PR TITLE
Add a katdal base and h5toms Dockerfile

### PR DESCRIPTION
**Pull request by sjperkins**
Do not merge this yet please.

### CODE REVIEW

**Comment by sjperkins** [comment]
@SpheMakh I've created a katdal base image Dockerfile, which I intend to use for an image which calls **h5toms.py**.

I doubt `stimela/cargo/cab` is the right place to put it though. Could you please advise on how to integrate a base image into stimela?

**Comment by sjperkins** [comment]
@bennahugo These Dockerfiles contain working katdal and h5toms images.

In particular the h5toms image can be used on an hdf5 file to produce an MS. I've tested this on my laptop with a hdf5 dataset from the vault.

**Comment by sjperkins** [comment]
@SpheMakh Can I please have input on how where to place the base image within Stimela?

**Comment by SpheMakh** [comment]
Hey @sjperkins, sorry for the delayed response. The way to do it is to push the katdal base image to docker-hub then add an 'executor' image based on the base image in stimela/cargo/cab/ like you did [here](https://github.com/SpheMakh/Stimela/pull/17/files#diff-a9b4482f46aad7719415d364ca0be81a). This executor image has to have a script that takes in parameters needed for the process (json file) and gives them to application which performs the process. See [this](https://github.com/SpheMakh/Stimela/tree/master/stimela/cargo/cab/moresane) (the script is src/run.py) executor image for an example.

**Comment by sjperkins** [comment]
@SpheMakh Thanks, uploading the base image was the missing link! I'm going to move the `katdal` Dockerfile to `stimela/cargo/base` for now, but I guess its appropriate to make it part of the radioastro/kern suite at some point.

**Pull request merged**
