### PR TITLE
Make Cubical great again !

### PR DESCRIPTION
**Pull request by KshitijT**
Fixes madmax-global-threshold name, adds parameters for nthread and nworker.

### CODE REVIEW

**Comment by bennahugo** [comment]
ok to test

**Comment by KshitijT** [comment]
retest this please

**Comment by KshitijT** [comment]
@SpheMakh , could you please force merge this pull request into master? The dd-worker in Meerkathi relies on the changes to the cubical parameter files and is currently failing. Please also rebuild the image on Jenkins used for the tests.

**Comment by SpheMakh** [comment]
Cannot force a merge, already got burned twice for last busy week's forced merges. It's next on the queue. If it's good it will go through in the next couple of hours

**Comment by KshitijT** [comment]
@bennahugo said that tests are not working for Stimela?

**Comment by SpheMakh** [comment]
They are working, they are just reporting failures if even there are no failures. But I will force the merge if they are no failures :)

**Pull request merged**
