### PR TITLE
add peak-based thresholding (peak-fraction)

### PR DESCRIPTION
**Pull request by SpheMakh**
Pinging @KshitijT 

https://github.com/SpheMakh/meerkathi/issues/18

### CODE REVIEW

**Comment by SpheMakh** [comment]
@KshitijT can you test?

**Comment by KshitijT** [comment]
Sure, I'll check it out.

**Comment by KshitijT** [comment]
@SpheMakh , getting this error while installing stimela to test this out:
```Step 1/6 : FROM stimela/wsclean:dev
manifest for stimela/wsclean:dev not found

  Traceback (most recent call last):
  File "/home/kshitij/stimela_etc/stimela_venv/bin/stimela", line 13, in <module>
    stimela.main([a for a in sys.argv[1:]])
  File "/home/kshitij/stimela_etc/stimela_venv/local/lib/python2.7/site-packages/stimela/__init__.py", line 520, in main
    _cmd(argv)
  File "/home/kshitij/stimela_etc/stimela_venv/local/lib/python2.7/site-packages/stimela/__init__.py", line 132, in build
    build_args=build_args, args=no_cache)
  File "/home/kshitij/stimela_etc/stimela_venv/local/lib/python2.7/site-packages/stimela/docker.py", line 37, in build
    build_path])
  File "/home/kshitij/stimela_etc/stimela_venv/local/lib/python2.7/site-packages/stimela/utils/__init__.py", line 72, in xrun
    raise SystemError('%s: returns errr code %d'%(command, process.returncode))
SystemError: docker build: returns errr code 1
```

**Comment by SpheMakh** [comment]
The image hadn't been built on dockerhub. Its built now, try again

**Comment by KshitijT** [comment]
I get the following error: 
```
/usr/local/lib/python2.7/dist-packages/astropy/config/configuration.py:541: ConfigurationMissingWarning: Configuration defaults will be used due to OSError:13 on None
  warn(ConfigurationMissingWarning(msg))
usage: cleanmask [-h] [-i IMAGE] [-o OUTPUT] [-s SIGMA] [-it ITERS]
                 [-nb BOXES] [-ol OVERLAP] [-mv MASK_VALUE] [-d]
                 [-t TOLERANCE] [-di DITER] [-nn]
                 [-ll {INFO,DEBUG,CRITICAL,WARNING}]
cleanmask: error: unrecognized arguments: --peak-fraction 0.5
running: cleanmask --image /home/kshitij/output/Stimela_peak_clean-sim-image.fits --output /home/kshitij/output/Stimela_peak_cleanmask0.fits --peak-fraction 0.5
Traceback (most recent call last):
  File "/code/run.py", line 25, in <module>
    utils.xrun(cab["binary"], args)
  File "/utils/utils/__init__.py", line 72, in xrun
    raise SystemError('%s: returns errr code %d'%(command, process.returncode))
SystemError: cleanmask: returns errr code 2
```

when using the peak-fraction option in the following manner:
```
pipeline.add('cab/cleanmask', 'mask0', {
    "image"  : imname0,
    "output" : maskname0,
    "dilate" : False,
    "peak-fraction" : 0.5,
    #"sigma"  : 20,
    },
    input=INPUT,
    output=OUTPUT,
    label='mask0:: Make mask based on peak fraction')
```

However, stimela cabs -i cleanmask shows peak-fraction as a valid option.

**Pull request merged**
