### PR TITLE
Custom CASA script runner

### PR DESCRIPTION
**Pull request by bennahugo**
@KshitijT @SpheMakh  As per title. Now we can run arbitrary in place jobs within the CASA framework without the rigmarole of having to  build new cabs or modify cabs. The primary use case for this is to have direct access to the tb and ms interfaces on demand. This is not meant to act as a replacement to casa task cabs, but rather a way to build measurement set information extraction and modification procedures on the fly.
```
  1 import stimela
  2 import os
  3 r = stimela.recipe.Recipe("HELLO_CASA", ms_dir="msdir", JOB_TYPE="docker")
  4 r.add("cab/casa", "getmaxvis", {
  5            "script": 
  6 """
  7 import numpy as np
  8 tb.open('{0:s}')
  9 d = tb.getcol("DATA")
 10 print "MAXIMUM VALUE OF DATASET IS", np.abs(d).max()
 11 tb.close()
 12 """.format(os.path.join(os.environ["HOME"], 
 13                         "msdir",
 14                         "1491291289.1ghz.1.1ghz.4hrs.ms"))
 15       }, input="input", output="output")
 16 r.run()
```

yielding:

```
(ddfvenv) > $ stimela run test_casa.py                                                                                                                                           
2019-06-24 18:19:43,307 - STIMELA - INFO - ---------------------------------
2019-06-24 18:19:43,307 - STIMELA - INFO - Stimela version 1.0.1
2019-06-24 18:19:43,307 - STIMELA - INFO - Sphesihle Makhathini <sphemakh@gmail.com>
2019-06-24 18:19:43,307 - STIMELA - INFO - Running: HELLO_CASA
2019-06-24 18:19:43,307 - STIMELA - INFO - ---------------------------------
2019-06-24 18:19:43,367 - STIMELA - INFO - Adding cab 'bhugo_cab/casa' to recipe. The container will be named 'getmaxvis'
INFO:STIMELA:Adding cab 'bhugo_cab/casa' to recipe. The container will be named 'getmaxvis'
2019-06-24 18:19:43,367 - STIMELA - INFO - Running job getmaxvis
INFO:STIMELA:Running job getmaxvis
2019-06-24 18:19:43,367 - STIMELA - INFO - STEP 1 :: getmaxvis_139988415580320
INFO:STIMELA:STEP 1 :: getmaxvis_139988415580320
INFO:root:Validating parameters...       CAB = casa
INFO:root:Parameters validated and saved. Parameter file is: stimela_parameter_files/getmaxvis-139988415580272156139318337.json
2019-06-24 18:19:43,367 - STIMELA - INFO - Instantiating container [getmaxvis-139988415580272156139318337]. The container ID is printed below.
INFO:STIMELA:Instantiating container [getmaxvis-139988415580272156139318337]. The container ID is printed below.
Running: docker create --user 1000:1000  -v /home/bhugo/workspace/stimela/stimela:/scratch/stimela:ro -v /home/bhugo/workspace/stimela_parameter_files:/configs:ro -v /home/bhugo/workspace/msdir:/home/bhugo/msdir:rw -v /home/bhugo/workspace/input:/input:ro -v /home/bhugo/workspace/output:/home/bhugo/output:rw -v /home/bhugo/workspace/output/log-getmaxvis.txt:/home/bhugo/workspace/output/logfile:rw  -e CONFIG=/configs/getmaxvis-139988415580272156139318337.json -e MSDIR=/home/bhugo/msdir -e INPUT=/input -e HOME=/home/bhugo/output -e OUTPUT=/home/bhugo/output -e LOGFILE=/home/bhugo/workspace/output/logfile  --name getmaxvis-139988415580272156139318337 --shm-size 1gb bhugo_cab/casa 
48aeba725e792cea7a90cf5742a8da4639b0d80c0a7dc057131c41d151c537f9

2019-06-24 18:19:44,426 - STIMELA - INFO - Starting container [getmaxvis-139988415580272156139318337]. Timeout set to -1. The container ID is printed below.
INFO:STIMELA:Starting container [getmaxvis-139988415580272156139318337]. Timeout set to -1. The container ID is printed below.
Running: docker start -a getmaxvis-139988415580272156139318337
Running: casa -c casajob.py.last

=========================================
The start-up time of CASA may vary
depending on whether the shared libraries
are cached or not.
=========================================

IPython 5.1.0 -- An enhanced Interactive Python.

CASA 5.4.1-31   -- Common Astronomy Software Applications

Found an existing telemetry logfile: /home/bhugo/output/.casa/casastats-541-31-242ac1102-20190624-160700.log
Telemetry initialized. Telemetry will send anonymized usage statistics to NRAO.
You can disable telemetry by setting environment variable with
export CASA_ENABLE_TELEMETRY=false
or by adding the following line in your ~/.casarc file:
EnableTelemetry: False
--> CrashReporter initialized.
MAXIMUM VALUE OF DATASET IS 66.8361150456


2019-06-24 18:19:52,437 - STIMELA - INFO - Container [getmaxvis-139988415580272156139318337] has executed successfully
INFO:STIMELA:Container [getmaxvis-139988415580272156139318337] has executed successfully
2019-06-24 18:19:52,437 - STIMELA - INFO - Runtime was 0:00:08.065871.
INFO:STIMELA:Runtime was 0:00:08.065871.
2019-06-24 18:19:52,478 - STIMELA - INFO - Container getmaxvis-139988415580272156139318337 has been stopped.
INFO:STIMELA:Container getmaxvis-139988415580272156139318337 has been stopped.
Running: docker rm getmaxvis-139988415580272156139318337
getmaxvis-139988415580272156139318337

2019-06-24 18:19:53,512 - STIMELA - INFO - Saving pipeline information in .last_hello_casa.json
INFO:STIMELA:Saving pipeline information in .last_hello_casa.json
2019-06-24 18:19:53,513 - STIMELA - INFO - Recipe executed successfully
INFO:STIMELA:Recipe executed successfully                                          
```

### CODE REVIEW

**Comment by bennahugo** [comment]
This is no different to a "pure python" lambda cab.

**Comment by SpheMakh** [comment]
How about we the python-casa core base instead? That way, the cab doesn't have to be trapped in a CASA environment

**Comment by SpheMakh** [comment]
Using python-casacore also avoids confusion, as users may mistake this for a general CASA cab which does everything that CASA can do.

**Comment by o-smirnov** [comment]
> How about we the python-casa core base instead? That way, the cab doesn't have to be trapped in a CASA environment

> Using python-casacore also avoids confusion, as users may mistake this for a general CASA cab which does everything that CASA can do.

+1 to that! Things are just much simpler and more Pythonic with python-casacore. And CASA itself is moving in that direction, if their announcements are to be believed.

**Comment by bennahugo** [comment]
retest this please

**Comment by bennahugo** [comment]
@SpheMakh cautiously optimistic that the jenkins system is up for stimela (only). It will email you if master is broken and it will email me if this does not pass.

**Comment by bennahugo** [comment]
retest this please

**Comment by SpheMakh** [comment]
changed the 'casa' cab to casa_script and added pycasacore cab

**Pull request merged**
