### PR TITLE
Change katdal to a custom install

### PR DESCRIPTION
**Pull request by sjperkins**
Use custom branches for casacore, python-casacore and katdal to get the new MS functionality.

### CODE REVIEW

**Comment by sjperkins** [comment]
Still testing, please do not merge

**Comment by sjperkins** [comment]
Its doing a custom build and install of casacore, so I wanted to avoid any possible conflicts. However, looking at kernsuite and stimela/base I think you're correct to say I should base ontop of them.

Still doing a vermeerkat run with it, will change this once I'm satisfied things are working.

**Comment by sjperkins** [comment]
@SpheMakh Testing h5toms conversion on ray with this PR now. Once the MS has been created, I'd like to get this merged. Could you then do a 0.2.7 release so that vermeerkat can depend on this functionality (https://github.com/ska-sa/vermeerkat/issues/39)?

**Comment by sjperkins** [comment]
@SpheMakh  I'm happy that this works.

**Comment by SpheMakh** [comment]
I'll start the ball rolling on releasing 0.2.7

**Comment by SpheMakh** [comment]
This image has failed to build on the docker hub for a couple of times. The error is not very informative though:
https://hub.docker.com/r/stimela/katdal/builds/bi7hj5rjmqeqkqwabzjw5et/

**Comment by sjperkins** [comment]
Is there a time limit on building dockerhub containers?

**Comment by SpheMakh** [comment]
Why don't you make a custom casacore image, then base the katdal image image on that. Also you can lower the size of the image by using `docker-apt-install` instead of `apt-get-install`

and, these packages are already in the stimela/base image
```
    software-properties-common \
    python-software-properties \
    python-pip \
    git \
```

**Comment by SpheMakh** [comment]
The docker-apt-install command (available on kernsuite images) is just a wrapper script that updates the apt cache before installing the package followed by a removal of the apt cache.

**Comment by SpheMakh** [comment]
`pyyaml` is also installed in the stimela/base image

**Comment by sjperkins** [comment]
> The docker-apt-install command (available on kernsuite images) is just a wrapper script that updates the apt cache before installing the package followed by a removal of the apt cache.

Yep, I'm currently doing that manually in the `Dockerfile`, but I'll use `docker-apt-install`.

I'll clean up the duplicates to avoid noops.

**Pull request merged**
