### PR TITLE
Conserve disk space (and bandwidth)

### PR DESCRIPTION
**Pull request by bennahugo**
First step towards conserving disk space.

### CODE REVIEW

**Comment by bennahugo** [comment]
retest this please

**Comment by bennahugo** [comment]
retest this please

**Comment by bennahugo** [comment]
maybe we can do check if tag exist in SINGULARITY_PULL folder before running singularity pull (with a force option)

**Comment by SpheMakh** [comment]
> maybe we can do check if tag exist in SINGULARITY_PULL folder before running singularity pull (with a force option) 

Could you implement this

**Comment by bennahugo** [comment]
retest this please

**Comment by bennahugo** [comment]
retest this please

**Comment by bennahugo** [comment]
Its running through and not setting the exit status to error
```
STIMELA: INFO: Adding cab '/var/lib/jenkins/jobs/PR_stimela/workspace/10/singularity_images/stimela_casa_1.0.1.img' to recipe. The container will be named 'delete_ms'
STIMELA: INFO: Running job simms_example
STIMELA: INFO: STEP 1 :: Creating MS
root: INFO: Validating parameters...       CAB = simms
root: DEBUG: Validating paramter direction
root: DEBUG: Validating paramter nchan
root: DEBUG: Validating paramter telescope
root: DEBUG: Validating paramter dfreq
root: DEBUG: Validating paramter freq0
root: DEBUG: Validating paramter dtime
root: DEBUG: Validating paramter synthesis
root: INFO: Parameters validated and saved. Parameter file is: stimela_parameter_files/simms_example-139831878484544156269667078.json
STIMELA: INFO: Instantiating container [simms_example-139831878484544156269667078]. Timeout set to 300. The container ID is printed below.
STIMELA: INFO: Recipe execution failed while running job simms_example
STIMELA: INFO: Completed jobs : []
STIMELA: INFO: Remaining jobs : ['listobs_example', 'simulator_example', 'imager_example_robust_0', 'delete_ms']
STIMELA: INFO: Logging remaining task: Some obs details
STIMELA: INFO: Logging remaining task: Simulating visibilities
STIMELA: INFO: Logging remaining task: Imaging MS, robust=2
STIMELA: INFO: Logging remaining task: Remove MS
STIMELA: INFO: Saving pipeline information in .last_singularity_test.json
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 2 tests in 19671.803s

FAILED (errors=2)
+ status=0
+ [ 0 -eq 0 ]
+ echo Jenkinsfile.sh build job ran successfully
Jenkinsfile.sh build job ran successfully
+ exit 0
An attempt to send an e-mail to empty list of recipients, ignored.
Adding one-line test results to commit status...
Setting status of 0b708b14b255f1c80efda50c78088f1d8fa1b112 to SUCCESS with url http://localhost:8081/job/PR_stimela/10/ and message: 'Build finished. No test results found.'
Setting status of 0b708b14b255f1c80efda50c78088f1d8fa1b112 to SUCCESS with url  and message: ' '
Triggering a new build of SERVER_STORAGE_SPACE
Finished: SUCCESS
```

**Comment by bennahugo** [comment]
at the moment I don't have any more time to debug this

**Comment by bennahugo** [comment]
never mind the last -e change should fix this. Lets see if the test fails. If it fails merge

**Comment by bennahugo** [comment]
ok @SpheMakh the test is working. There are failures as per:
http://localhost:8081/job/PR_stimela/16/console

But I leave these for you to fix. Can you please merge this PR so I can start working on MeerKATHI

**Pull request merged**
