### PR TITLE
use meqtrees base image with latest owlcat

### PR DESCRIPTION
**Pull request by SpheMakh**

### CODE REVIEW

**Comment by bennahugo** [comment]
Lets please get the tests working again before merging

**Comment by SpheMakh** [comment]
Hi @bennahugo I'm getting strange "permision denied error" from setuptools via meqtrees, I cannot reproduce this but I've noticed that the version of singularity on the test machine is older than the one I'm using (as well as the version on most of our machines). Could you please update singularity in the test machine to be >=2.6.0-dist

**Comment by SpheMakh** [comment]
Here is the error
```
Running: meqtree-pipeliner.py  --mt 4 -c /scratch/code//tdlconf.profiles [sim] ms_sel.input_column=DATA ms_sel.field_index=0 ms_sel.msname=/scratch/msdir/meerkat_simulation_example.ms me.sky.tiggerskymodel=1 me.use_smearing=0 sim_mode="sim only" noise_stddev=0.18581724893 ms_sel.ddid_index=0 ms_sel.tile_size=64 tiggerlsm.filename=/scratch/input/nvss1deg.lsm.html ms_sel.output_column=CORRECTED_DATA /usr/lib/python2.7/dist-packages/Cattery/Siamese/turbo-sim.py =_simulate_MS
Traceback (most recent call last):
  File "/usr/bin/meqtree-pipeliner.py", line 9, in <module>
    import Timba.utils
  File "/usr/lib/python2.7/dist-packages/Timba/utils.py", line 35, in <module>
    from Kittens.utils import verbosity
  File "/usr/lib/python2.7/dist-packages/Kittens/utils.py", line 38, in <module>
    from astropy.io import fits
  File "/usr/lib/python2.7/dist-packages/astropy/__init__.py", line 116, in <module>
    _check_numpy()
  File "/usr/lib/python2.7/dist-packages/astropy/__init__.py", line 105, in _check_numpy
    requirement_met = minversion(numpy, __minimum_numpy_version__)
  File "/usr/lib/python2.7/dist-packages/astropy/utils/introspection.py", line 156, in minversion
    from pkg_resources import parse_version
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws = cls()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 567, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 623, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2056, in find_on_path
    for dist in factory(fullpath):
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2126, in distributions_from_metadata
    root, entry, metadata, precedence=DEVELOP_DIST,
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2583, in from_location
    py_version=py_version, platform=platform, **kw
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2985, in _reload_version
    md_version = self._get_version()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2763, in _get_version
    version = _version_from_file(lines)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2547, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2758, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1902, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1888, in get_metadata
    with io.open(self.path, encoding='utf-8', errors="replace") as f:
IOError: [Errno 13] Permission denied: '/usr/lib/python2.7/dist-packages/.wh.setuptools-39.0.1.egg-info'

Traceback (most recent call last):
  File "/scratch/code/run.py", line 140, in <module>
    utils.xrun(cab['binary'], prefix + args + suffix)
  File "/scratch/stimela/utils/__init__.py", line 111, in xrun
    raise StimelaCabRuntimeError('%s: returns errr code %d' % (command, process.returncode))
utils.StimelaCabRuntimeError: meqtree-pipeliner.py: returns errr code 1

Running: singularity instance.stop 7cc
Stopping 7cc instance of /var/lib/jenkins/jobs/PR_stimela/workspace/46/singularity_images/stimela_meqtrees_1.1.3.img (PID=26669)

```

**Comment by bennahugo** [comment]
I don't think its a singularity issue at all as discussed. I have a strong suspicion it is because you are reusing tags. These tags are not forcefully redownload any more because it takes hours to redownload the entire set. I think you should rather keep to the policy of not reusing tags (delete those that don't work upstream on the hub and tag the new ones with a unique tag).

**Pull request merged**
